
// This file has been generated by the GUI designer. Do not modify.
namespace FirstProgramGUI
{
	public partial class MultWindow
	{
		private global::Gtk.Fixed fixed7;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FirstProgramGUI.MultWindow
			this.Name = "FirstProgramGUI.MultWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MultWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child FirstProgramGUI.MultWindow.Gtk.Container+ContainerChild
			this.fixed7 = new global::Gtk.Fixed ();
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			this.Add (this.fixed7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
